"""Create user and meal tables

Revision ID: b71cd69b97c0
Revises: 
Create Date: 2025-11-06 16:29:46.797144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71cd69b97c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('daily_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('total_calories', sa.Float(), nullable=False),
    sa.Column('target_calories', sa.Float(), nullable=False),
    sa.Column('total_protein', sa.Float(), nullable=False),
    sa.Column('total_carbs', sa.Float(), nullable=False),
    sa.Column('total_fat', sa.Float(), nullable=False),
    sa.Column('total_sodium', sa.Float(), nullable=False),
    sa.Column('total_sugar', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('improvement', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_scores_score_date'), 'daily_scores', ['score_date'], unique=False)
    op.create_index(op.f('ix_daily_scores_user_id'), 'daily_scores', ['user_id'], unique=False)
    op.create_table('food_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('food_name', sa.String(length=200), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('sodium', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_analyses_user_id'), 'food_analyses', ['user_id'], unique=False)
    op.create_table('meal_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_recommendations_recommendation_date'), 'meal_recommendations', ['recommendation_date'], unique=False)
    op.create_index(op.f('ix_meal_recommendations_user_id'), 'meal_recommendations', ['user_id'], unique=False)
    op.create_table('meal_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('meal_date', sa.Date(), nullable=False),
    sa.Column('meal_time', sa.DateTime(), nullable=False),
    sa.Column('portion', sa.Float(), nullable=False),
    sa.Column('total_calories', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_records_meal_date'), 'meal_records', ['meal_date'], unique=False)
    op.create_index(op.f('ix_meal_records_user_id'), 'meal_records', ['user_id'], unique=False)
    op.create_table('user_health_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('body_type', sa.String(length=20), nullable=False),
    sa.Column('activity_level', sa.String(length=50), nullable=False),
    sa.Column('recommended_calories', sa.Float(), nullable=False),
    sa.Column('has_allergy', sa.Boolean(), nullable=False),
    sa.Column('allergy_info', sa.Text(), nullable=True),
    sa.Column('medical_condition', sa.Text(), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('diseases', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_health_info_user_id'), 'user_health_info', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_health_info_user_id'), table_name='user_health_info')
    op.drop_table('user_health_info')
    op.drop_index(op.f('ix_meal_records_user_id'), table_name='meal_records')
    op.drop_index(op.f('ix_meal_records_meal_date'), table_name='meal_records')
    op.drop_table('meal_records')
    op.drop_index(op.f('ix_meal_recommendations_user_id'), table_name='meal_recommendations')
    op.drop_index(op.f('ix_meal_recommendations_recommendation_date'), table_name='meal_recommendations')
    op.drop_table('meal_recommendations')
    op.drop_index(op.f('ix_food_analyses_user_id'), table_name='food_analyses')
    op.drop_table('food_analyses')
    op.drop_index(op.f('ix_daily_scores_user_id'), table_name='daily_scores')
    op.drop_index(op.f('ix_daily_scores_score_date'), table_name='daily_scores')
    op.drop_table('daily_scores')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###

